# Generated by Django 3.1 on 2023-04-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_hobby_meet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='job',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
