# Generated by Django 3.1 on 2023-04-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20230414_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hobbies',
            field=models.ManyToManyField(to='person.Hobby'),
        ),
    ]
