# Generated by Django 3.1 on 2023-04-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20230414_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
    ]
