# Generated by Django 3.1 on 2023-04-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20230417_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='type_invoce',
            new_name='invoice_type',
        ),
    ]
