# Generated by Django 3.1 on 2023-04-17 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=120, unique=True, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('man', models.BooleanField(default=True)),
                ('woman', models.BooleanField(default=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('purchase_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_image', models.ImageField(upload_to='product')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='product')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='product')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='product')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='product')),
                ('video', models.URLField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('colors', models.ManyToManyField(to='product.Colors')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
